import Accordion from "@/components/accordion";
import Header from "@/components/header";
import Image from "next/image";
import { CgArrowLongUpR } from "react-icons/cg";
import { BsQuestionLg } from "react-icons/bs";
import { FaCheckCircle } from "react-icons/fa";
import LogoLoop from "@/components/LogoLoop";
import { MdOutlineGridGoldenratio } from "react-icons/md";
import Link from "next/link";
import SplitText from "@/components/SplitText";
import AnimatedContent from "@/components/AnimatedContent";
import Roadmap from "@/components/roadMap";
import PartnersAndNews from "@/components/partnersAndNews";
import RippleGrid from "@/components/RippleGrid";

export default function Home() {
  const accordionList = [
    {
      question: "What is Capital Market Hub?",
      answer:
        "Capital Market Hub is a multi-regulated global forex and shares broker that provides a trading and investment platform for cryptocurrencies, stocks, and CFDs.",
    },
    {
      question: "How do I create an account?",
      answer:
        "You can create an account by clicking on the 'Get Started' button on our homepage and following the registration process.",
    },
    {
      question: "What trading instruments are available?",
      answer:
        "We offer a wide range of trading instruments including major, minor, and exotic currency pairs, global stocks, popular cryptocurrencies, and CFDs on various assets.",
    },
    {
      question: "Is my money safe with Capital Market Hub?",
      answer:
        "Yes, we are a regulated broker and prioritize the safety and security of our clients' funds. We use advanced technology to ensure secure transactions.",
    },
    {
      question: "What customer support options are available?",
      answer:
        "We offer 24/7 customer care support to assist you with any queries or issues you may have.",
    },
  ];

  const features = [
    "Capital Market Hub is completely free of charge!",
    "Capital Market Hub can help you trade in both the manual and automatic formats with an average of 87.35% Win Rate across all compatible brokers.",
    "Capital Market Hub is fully SSL and highly secure thereby providing little or no chance for your personal details to be phished by cyber-criminals.",
    "Our signals are generated by a complex set of mathematical operations involving the indicators and the method you’ve selected for trading.",
    "Capital Market Hub can be synced with the Top-Class brokers in the market providing you with security for your capital and a peace of mind.",
  ];

  const imageLogos = [
    {
      src: "https://www.capitalex.co/coin/eth.png",
      alt: "Company 1",
      href: "https://company1.com",
    },
    {
      src: "https://www.capitalex.co/coin/bch.png",
      alt: "Company 2",
      href: "https://company2.com",
    },
    {
      src: "https://www.capitalex.co/coin/lit.png",
      size: "100",
      alt: "Company 3",
      href: "https://company3.com",
    },
    {
      src: "https://www.capitalex.co/coin/tet.png",
      alt: "Company 3",
      href: "https://company3.com",
    },
    {
      src: "https://www.capitalex.co/coin/shib.png",
      alt: "Company 3",
      href: "https://company3.com",
    },
    {
      src: "https://www.capitalex.co/coin/doge.png",
      alt: "Company 3",
      href: "https://company3.com",
    },
    {
      src: "https://www.capitalex.co/coin/bnb.png",
      alt: "Company 3",
      href: "https://company3.com",
    },
    {
      src: "https://www.capitalex.co/coin/sol.png",
      alt: "Company 3",
      href: "https://company3.com",
    },
    {
      src: "https://www.capitalex.co/coin/crypto.png",
      alt: "Company 3",
      href: "https://company3.com",
    },
    {
      src: "https://www.capitalex.co/coin/cad.png",
      alt: "Company 3",
      href: "https://company3.com",
    },
  ];

  const plans = [
    {
      name: "BRONZE",
      image: "/images/bronze.png", // replace with your image path
      minDeposit: "$3,000",
      maxDeposit: "$10,000",
      duration: "3 Weeks",
    },
    {
      name: "SILVER",
      image: "/images/silver.png", // replace with your image path
      minDeposit: "$10,000",
      maxDeposit: "$50,000",
      duration: "4-6 Weeks",
    },
    {
      name: "GOLD",
      image: "/images/gold.png", // replace with your image path
      minDeposit: "$50,000",
      maxDeposit: "UNLIMITED",
      duration: "9 Weeks",
    },
  ];

  const roadmapData = [
    {
      quarter: "Q1 2018",
      period: "January - March 2018",
      description:
        "We started capitalex and worked on creating a robust platform for efficient trading.",
    },
    {
      quarter: "Q2 2018",
      period: "April - June 2018",
      description:
        "Consolidating our holds in the market with major diversification into emerging currencies.",
    },
    {
      quarter: "Q3 2018",
      period: "July - September 2018",
      description: "Capitalex kicks off its trading platform.",
    },
    {
      quarter: "Q4 2018",
      period: "October - December 2018",
      description:
        "Building of a consolidated market share running on a connected system.",
    },
    {
      quarter: "Q1 2019",
      period: "January - March 2019",
      description: "Expansion into global markets with new partnerships.",
    },
    {
      quarter: "Q2 2019",
      period: "April - June 2019",
      description: "Launching advanced analytics and AI-driven trading tools.",
    },
    {
      quarter: "Q4 2018",
      period: "October - December 2018",
      description:
        "Building of a consolidated market share running on a connected system.",
    },
  ];

  return (
    <>
      <Header />
      {/* bg-[#0a0a1a] */}
      <main className="text-white">
        {/* HERO SECTION */}
        <section className="min-h-screen flex flex-col lg:flex-row items-center justify-center gap-8 px-6 lg:px-16 py-20 mt-10">
          <div className="max-w-2xl text-center lg:text-left">
            <h1 className="text-white text-4xl sm:text-5xl lg:text-6xl font-bold">
              <SplitText
                text="Multi-regulated Global Forex and Shares Broker"
                className="text-[#5479ff]"
                delay={45}
                duration={0.1}
                ease="power3.out"
                splitType="chars"
                from={{ opacity: 0, y: 40 }}
                to={{ opacity: 1, y: 0 }}
                threshold={0.1}
                rootMargin="-100px"
                // textAlign=""
                // onLetterAnimationComplete={handleAnimationComplete}
              />
            </h1>

            <AnimatedContent
              distance={150}
              direction="vertical"
              reverse={false}
              duration={1.2}
              ease="bounce.out"
              initialOpacity={0.2}
              animateOpacity
              scale={1.1}
              threshold={0.2}
              delay={0.3}
            >
              <p className="text-white text-base sm:text-lg mt-6 mb-10 leading-relaxed">
                Regulated Trading & Investment platform for cryptocurrencies,
                Stocks, CFD that standarizes data & operations with blockchain
                technology. We provide user-friendly, efficient and secure
                trading & investment solutions utilizing blockchain technology.
              </p>
            </AnimatedContent>
            <AnimatedContent
              distance={150}
              direction="horizontal"
              reverse={false}
              duration={1.7}
              ease="power3.out"
              initialOpacity={0.2}
              animateOpacity
              // scale={1.1}
              threshold={0.2}
              delay={0.4}
            >
              <Link
                href="/register"
                className="bg-red-600 text-white px-8 sm:px-12 py-3 sm:py-4 rounded-lg"
              >
                Get Started
              </Link>
            </AnimatedContent>
          </div>
          <div className="max-w-xl w-full">
            <AnimatedContent
              distance={350}
              direction="horizontal"
              reverse={false}
              duration={1.2}
              ease="bounce.out"
              initialOpacity={0.2}
              animateOpacity
              scale={1.1}
              threshold={0.2}
              delay={0.3}
            >
              <Image
                src="/images/heroImage.png"
                alt="Hero Image"
                width={900}
                height={400}
                priority
                className="w-full h-auto"
              />
            </AnimatedContent>
          </div>
        </section>

        {/* WHY CHOOSE US */}
        <section
          className="flex flex-col lg:flex-row items-center justify-center gap-8 min-h-[70vh] px-6 lg:px-20 py-16"
          id="about"
        >
          <AnimatedContent
            distance={-150}
            direction="vertical"
            reverse={false}
            duration={1.2}
            ease="bounce.out"
            initialOpacity={0}
            animateOpacity
            scale={1.1}
            threshold={0.2}
            delay={0.2}
          >
            <div className="max-w-2xl text-center lg:text-left">
              <h2 className="text-3xl sm:text-4xl font-bold">
                About Capital Market Hub
              </h2>
              <p className="text-base sm:text-lg mt-6 mb-6 leading-relaxed">
                We are committed to providing our clients with the best trading
                experience possible. Our platform is designed to be
                user-friendly, efficient, and secure. We offer a wide range of
                trading instruments, including cryptocurrencies, stocks, and
                CFDs. Our team of experienced professionals is dedicated to
                helping our clients succeed in the financial markets.
              </p>
              <Link
                href="/register"
                className="bg-gray-900 text-white px-8 sm:px-12 py-3 sm:py-4 rounded-lg"
              >
                Get Started &gt;
              </Link>
            </div>
          </AnimatedContent>
          <AnimatedContent
            distance={-150}
            direction="vertical"
            reverse={false}
            duration={1.2}
            ease="bounce.out"
            initialOpacity={0}
            animateOpacity
            scale={1.1}
            threshold={0.2}
            // delay={0.1}
          >
            <div className="max-w-2xl">
              <ul className="text-base sm:text-lg flex flex-col gap-4 list-none">
                <li>
                  &#9653; Customer care support available 24/7 to assist you
                  with any queries or issues.
                </li>
                <li>
                  &#9653; Fast and secure transactions powered by advanced
                  technology.
                </li>
                <li>
                  &#9653; Enjoy low fees and tight spreads, maximizing your
                  potential returns and minimizing trading costs.
                </li>
                <li>
                  &#9653; Access advanced trading tools and analytics to
                  optimize your strategies.
                </li>
                <li>
                  &#9653; Trade on a regulated and secure platform that
                  prioritizes your safety.
                </li>
              </ul>
            </div>
          </AnimatedContent>
        </section>

        <section className="py-16 px-6 md:px-20 text-white relative overflow-hidden">
          <AnimatedContent
            distance={150}
            direction="vertical"
            reverse={false}
            duration={1.2}
            ease="bounce.out"
            initialOpacity={0.1}
            animateOpacity
            scale={1.1}
            threshold={0.01}
            // delay={0.1}
          >
            <h2 className="text-4xl md:text-4xl font-bold mb-6 text-center md:text-left">
              Why Choose Us?
            </h2>
          </AnimatedContent>
          <AnimatedContent
            distance={150}
            direction="vertical"
            reverse={false}
            duration={1.2}
            ease="power3.out"
            initialOpacity={0.1}
            animateOpacity
            scale={1.1}
            threshold={0.01}
            delay={0.2}
          >
            <p className="text-gray-300 mb-6 text-center md:text-left">
              capital market hub ?
            </p>
          </AnimatedContent>
          <div className="max-w-7xl mx-auto grid md:grid-cols-2 gap-12 items-center">
            {/* Left - Image */}
            <AnimatedContent
              distance={150}
              direction="vertical"
              reverse={false}
              duration={1.2}
              ease="bounce.out"
              initialOpacity={0.8}
              animateOpacity
              scale={1.1}
              threshold={0.01}
              delay={0.3}
            >
              <div className="relative">
                <Image
                  src="https://cdn.prod.website-files.com/67c5ccce25ee4e53514167ac/68c12e5ca46b640e39bc2d63_67ebc0595811379a230664aa_support-%2526-resistance.webp"
                  alt="Trading Dashboard"
                  width={600}
                  height={400}
                  className="rounded-lg shadow-lg"
                />
              </div>
            </AnimatedContent>

            {/* Right - Content */}
            <div>
              <ul className="space-y-6">
                {features.map((feature, i) => (
                  <AnimatedContent
                    key={i}
                    distance={150}
                    direction="vertical"
                    reverse={false}
                    duration={1.2}
                    ease="power3.out"
                    initialOpacity={0.8}
                    animateOpacity
                    scale={1.1}
                    threshold={0.01}
                    delay={i / 10}
                  >
                    <li className="flex items-start gap-3 text-xl">
                      <FaCheckCircle className="text-gray-900 mt-1 text-4xl border-2 rounded-full border-l-gray-600 border-t-red-400 border-r-green-600 bg-teal-700 flex-shrink-0" />
                      <span className="text-gray-200">{feature}</span>
                    </li>
                  </AnimatedContent>
                ))}
              </ul>
            </div>
          </div>
        </section>

        {/* OUR SERVICES */}
        <section className="px-6 lg:px-20 py-16 min-h-[60vh]" id="investment">
          <AnimatedContent
            distance={150}
            direction="vertical"
            reverse={false}
            duration={1.2}
            ease="power3.out"
            initialOpacity={0.8}
            animateOpacity
            scale={1.1}
            threshold={0.01}
            // delay={0.1}
          >
            <h2 className="text-3xl sm:text-5xl font-bold text-center">
              Service we Provide
            </h2>
          </AnimatedContent>
          <AnimatedContent
            distance={150}
            direction="vertical"
            reverse={false}
            duration={1.2}
            ease="power3.out"
            initialOpacity={0.8}
            animateOpacity
            scale={1.1}
            threshold={0.01}
            delay={0.2}
          >
            <div className="flex gap-12 mt-12">
              <div className="flex flex-col lg:flex-row md:justify-around  justify-center text-center min-h-[70vh]">
                <li className="flex flex-col gap-4 max-w-sm border-r border-gray-700 px-4">
                  &#9653;{" "}
                  <strong className="text-gray-400 text-xl uppercase">
                    Customer Care Support 24/7
                  </strong>
                  We are Online 247.
                  <CgArrowLongUpR className="text-red-500 text-5xl mx-auto" />
                </li>
                <li className="flex flex-col gap-4 max-w-sm self-center border-x border-gray-700 px-4">
                  &#9653;{" "}
                  <strong className="text-gray-400 text-xl uppercase">
                    Payment Methods
                  </strong>
                  capital market hub Inc supports Bitcoin, Etheruem, Litecoin
                  and XRP. For any other preferred payment method kindly contact
                  support@capitalmarkethub.co
                  <CgArrowLongUpR className="text-red-500 text-5xl mx-auto" />
                </li>
                {/* </div>
            <div className="flex flex-col lg:flex-row md:gap-8 md:justify-around  justify-center items-center text-center text-xl"> */}
                <li className="flex flex-col gap-4 max-w-sm self-end border-x border-gray-700 px-4">
                  &#9653;{" "}
                  <strong className="text-gray-400 text-xl uppercase">
                    Secured Company
                  </strong>
                  capital market hub is inbuilt with a 2FA security to ensure
                  the maximum security and safety of your investments.
                  <CgArrowLongUpR className="text-red-500 text-5xl mx-auto" />
                </li>
                <li className="flex flex-col gap-4 max-w-sm self-center border-l border-gray-700 px-4 md:mb-16">
                  &#9653;{" "}
                  <strong className="text-gray-400 text-xl uppercase">
                    Cryptocurrency Investments
                  </strong>{" "}
                  Start Earning Now On capitalmarkethub.co
                  <CgArrowLongUpR className="text-red-500 text-5xl mx-auto" />
                </li>
              </div>
            </div>
          </AnimatedContent>
        </section>

        {/* HOW IT WORKS */}

        {/* <section className="px-6 lg:px-20 py-16 min-h-[80vh]">
          <h2 className="text-4xl sm:text-4xl font-bold text-center lg:text-left">
            How It Works
          </h2>
          <p className="text-base sm:text-lg mt-6 mb-6 leading-relaxed text-center lg:text-left">
            Our platform is designed to provide a seamless trading experience.
            Here&apos;s how it works:
          </p>

          <ol className="flex flex-col gap-8 lg:flex-row lg:gap-6 items-center justify-center">
      
            <AnimatedContent
              distance={150}
              direction="vertical"
              reverse={false}
              duration={1.2}
              ease="power3.out"
              initialOpacity={0.8}
              animateOpacity
              scale={1.1}
              threshold={0.01}
              delay={0.2} 
            >
              <li className="flex flex-col gap-4 border p-5 rounded-lg max-w-lg w-full bg-gray-900">
                <p>
                  <strong>Sign Up:</strong> Create an account in minutes and
                  verify your identity.
                </p>
                <Image
                  src="/images/auth.svg"
                  alt="Sign Up"
                  width={200}
                  height={80}
                  className="rounded-lg size-72"
                />
              </li>
            </AnimatedContent>

  
            <AnimatedContent
              distance={150}
              direction="vertical"
              reverse={false}
              duration={1.2}
              ease="power3.out"
              initialOpacity={0.8}
              animateOpacity
              scale={1.1}
              threshold={0.01}
              delay={0.4} 
            >
              <li className="flex flex-col gap-4 border p-5 rounded-lg max-w-lg w-full bg-gray-900">
                <p>
                  <strong>Fund Your Account:</strong> Deposit funds using
                  various payment methods.
                </p>
                <Image
                  src="/images/money.svg"
                  alt="Choose a Plan"
                  width={200}
                  height={80}
                  className="rounded-lg size-72"
                />
              </li>
            </AnimatedContent>

            <AnimatedContent
              distance={150}
              direction="vertical"
              reverse={false}
              duration={1.2}
              ease="power3.out"
              initialOpacity={0.8}
              animateOpacity
              scale={1.1}
              threshold={0.01}
              delay={0.6}
            >
              <li className="flex flex-col gap-4 border p-5 rounded-lg max-w-lg w-full bg-gray-900">
                <p>
                  <strong>Start Trading:</strong> Access our trading platform
                  and start trading a wide range of instruments.
                </p>
                <Image
                  src="/images/trading.svg"
                  alt="Deposit"
                  width={200}
                  height={80}
                  className="rounded-lg size-72"
                />
              </li>
            </AnimatedContent>
          </ol>
        </section> */}

        <section className="relative px-6 lg:px-20 py-20 bg-gradient-to-b from-gray-950 via-gray-900 to-gray-950 text-white">
          <div className="max-w-6xl mx-auto">
            {/* Heading */}
            <div className="text-center lg:text-left mb-14">
              <h2 className="text-4xl sm:text-5xl font-extrabold tracking-tight">
                How It Works
              </h2>
              <p className="mt-6 text-lg leading-relaxed max-w-2xl mx-auto lg:mx-0 text-gray-300">
                Our platform is designed to provide a seamless trading
                experience. Here&apos;s how it works:
              </p>
            </div>

            {/* Steps */}
            <ol className="flex flex-col lg:flex-row gap-10 lg:gap-6 items-center lg:items-stretch justify-center">
              {/* Step 1 */}
              <li className="flex flex-col items-center lg:items-start gap-6 border border-gray-700 rounded-2xl p-8 bg-gray-900/70 hover:bg-gray-800/80 transition shadow-lg w-full max-w-sm">
                <Image
                  src="/images/auth.svg"
                  alt="Sign Up"
                  width={160}
                  height={160}
                  className="rounded-xl"
                />
                <p className="text-center lg:text-left text-base leading-relaxed">
                  <strong className="block text-blue-400">Sign Up:</strong>
                  Create an account in minutes and verify your identity.
                </p>
              </li>

              {/* Step 2 */}
              <li className="flex flex-col items-center lg:items-start gap-6 border border-gray-700 rounded-2xl p-8 bg-gray-900/70 hover:bg-gray-800/80 transition shadow-lg w-full max-w-sm">
                <Image
                  src="/images/money.svg"
                  alt="Fund Account"
                  width={160}
                  height={160}
                  className="rounded-xl"
                />
                <p className="text-center lg:text-left text-base leading-relaxed">
                  <strong className="block text-green-400">
                    Fund Your Account:
                  </strong>
                  Deposit funds easily using multiple payment methods.
                </p>
              </li>

              {/* Step 3 */}
              <li className="flex flex-col items-center lg:items-start gap-6 border border-gray-700 rounded-2xl p-8 bg-gray-900/70 hover:bg-gray-800/80 transition shadow-lg w-full max-w-sm">
                <Image
                  src="/images/trading.svg"
                  alt="Start Trading"
                  width={160}
                  height={160}
                  className="rounded-xl"
                />
                <p className="text-center lg:text-left text-base leading-relaxed">
                  <strong className="block text-yellow-400">
                    Start Trading:
                  </strong>
                  Access our platform and trade a wide range of instruments.
                </p>
              </li>
            </ol>
          </div>
        </section>

        <section className=" py-16 px-6 md:px-20 text-white">
          <div className="max-w-7xl mx-auto text-center">
            <h2 className="text-3xl md:text-4xl font-bold mb-12">
              Our Investment Plans
            </h2>

            {/* Cards */}
            {/* bg-[#1b1b2d] */}
            <div className="grid md:grid-cols-3 gap-10">
              {plans.map((plan, i) => (
                <AnimatedContent
                  distance={150}
                  direction="vertical"
                  reverse={false}
                  duration={1.2}
                  ease="power3.out"
                  initialOpacity={0.8}
                  animateOpacity
                  scale={1.1}
                  threshold={0.01}
                  delay={i / 10}
                  key={i}
                >
                  <div className="bg-gray-900 rounded-lg shadow-lg px-6 py-8 flex flex-col items-center hover:scale-105 transition-transform">
                    {/* Plan Image */}
                    <MdOutlineGridGoldenratio className="text-9xl my-3" />

                    {/* Plan Name */}
                    <h3 className="text-xl font-bold mb-6">{plan.name}</h3>

                    {/* Features */}
                    <ul className="space-y-3 text-xl">
                      <li>
                        <span className="font-semibold">Minimum Deposit:</span>{" "}
                        {plan.minDeposit}
                      </li>
                      <li>
                        <span className="font-semibold">Maximum Deposit:</span>{" "}
                        {plan.maxDeposit}
                      </li>
                      <li>Risk management</li>
                      <li>Standard Options</li>
                      <li>Account manager</li>
                      <li>
                        <span className="font-semibold">
                          Contract Duration:
                        </span>{" "}
                        {plan.duration}
                      </li>
                    </ul>
                  </div>
                </AnimatedContent>
              ))}
            </div>

            {/* Call to Action */}
            <AnimatedContent
              distance={250}
              direction="horizontal"
              reverse={false}
              duration={1.2}
              ease="power3.out"
              initialOpacity={0.8}
              animateOpacity
              scale={1.1}
              threshold={0.01}
              // delay={0,1}
            >
              <div className="mt-12">
                <a
                  href="#"
                  className="inline-block bg-gray-600 hover:bg-gray-700 text-white font-semibold px-6 py-3 rounded-lg"
                >
                  SIGN UP FOR MORE HIGHER INVESTMENT PLANS TODAY
                </a>
              </div>
            </AnimatedContent>
          </div>
        </section>

        <Roadmap roadmapData={roadmapData} />
        <PartnersAndNews />

        <section className="pt-20">
          <h2 className="text-4xl text-center font-mono font-bold">
            At Capital hub Market <br /> We support
          </h2>
          <div className="min-h-[50vh] flex justify-center items-center">
            <LogoLoop
              logos={imageLogos}
              speed={120}
              direction="left"
              logoHeight={125}
              gap={50}
              pauseOnHover
              scaleOnHover
              fadeOut
              fadeOutColor="#020615"
              ariaLabel="Technology partners"
            />
          </div>
        </section>

        {/* CTA */}
        <section>
          <AnimatedContent
            distance={250}
            direction="vertical"
            reverse={false}
            duration={1.2}
            ease="power3.out"
            initialOpacity={0.8}
            animateOpacity
            scale={1.1}
            threshold={0.01}
            // delay={0,1}
          >
            <div className=" text-white text-center p-10">
              <h2 className="text-3xl sm:text-4xl font-bold mb-4">
                Ready to Get Started?
              </h2>
              <p className="text-base sm:text-lg mb-6">
                Join thousands of traders and investors who trust us for their
                trading needs.
              </p>
              <button className="bg-red-600 text-white px-8 sm:px-12 py-3 sm:py-4 rounded-lg">
                Sign Up Now
              </button>
            </div>
          </AnimatedContent>
        </section>

        {/* FAQ */}
        <section
          className="flex flex-col items-center py-16 gap-8 min-h-[80vh] px-6"
          id="faq"
        >
          <div className="max-w-3xl text-center flex flex-col gap-6">
            <span className="bg-gray-400 flex justify-center items-center text-xs p-2 text-gray-700">
              FAQ QUESTION <BsQuestionLg className="text-red-500 ml-1" />
            </span>
            <h2 className="text-2xl sm:text-3xl font-bold">
              Frequently Asked Questions
            </h2>
            <p className="text-base sm:text-lg px-2 sm:px-8">
              Below we’ve provided answers to the most frequently asked
              questions. If you have any other questions, please get in touch.
            </p>
            <Accordion accordionList={accordionList} />
          </div>
        </section>

        {/* CONTACT */}
        <section
          className="flex justify-center items-center px-6 lg:px-20 py-16 min-h-[60vh]"
          id="contact"
        >
          <div
            style={{
              position: "relative",
              height: "500px",
              overflow: "hidden",
            }}
          >
            <RippleGrid
              enableRainbow={false}
              gridColor="#ffffff"
              rippleIntensity={0.05}
              gridSize={10}
              gridThickness={15}
              mouseInteraction={true}
              mouseInteractionRadius={1.2}
              opacity={0.8}
            />
          </div>

          <div className="max-w-2xl">
            <h2 className="text-3xl sm:text-4xl font-bold">Contact Us</h2>
            <p className="text-base sm:text-lg mt-6 mb-6 leading-relaxed">
              Have questions or need assistance? Our support team is here to
              help. Reach out to us via email, phone, or live chat.
            </p>
            <ul className="text-base sm:text-lg flex flex-col gap-3 list-none">
              <li>&#9653; Email: support@capitalmarkethub.com</li>
              <li>&#9653; Phone: +1 (800) 123-4567</li>
              <li>&#9653; Live Chat: Available on our website</li>
            </ul>
          </div>
        </section>

        {/* FOOTER */}
        <footer>
          <div className="bg-black text-white text-center p-6 sm:p-10">
            <p className="text-sm sm:text-base">
              &copy; 2025Capital Market Hub. All rights reserved.
            </p>
          </div>
        </footer>
      </main>
    </>
  );
}
